sudo: false
language: python
python:
  - "3.6"
install:
  - pip install mypy
  - pip install coveralls
script:
  - mypy -p bdemeta -m tests/cmake_parser
  - coverage run --omit="tests/test_*","tests/**__init__.py" -m unittest discover
after_success:
  - coveralls
