sudo: false
language: python
python:
  - "3.6"
install:
  - pip install mypy
  - pip install coveralls
script:
  - mypy -p bdemeta -m tests/cmake_parser
  - coverage run -m unittest
after_success:
  - coveralls
